djangoapp/contact/urls.py
from django.urls import path
from contact import views

app_name = 'contact'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),

    # Contact (CRUD)
    path('contact/<int:contact_id>/detail/', views.contact, name='contact'),
    path('contact/create/', views.create, name='create'),
    path('contact/<int:contact_id>/update/', views.update, name='update'),
    path('contact/<int:contact_id>/delete/', views.delete, name='delete'),

    # User (CRUD)

    path('user/create/', views.register, name='register'),
    path('user/login/', views.login_view, name='login'),
    path('user/logout/', views.logout_view, name='logout'),
    path('user/update/', views.user_update, name='user_update'),


]

djangoapp/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

djangoapp/contact/models.py
from typing import Any
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Contacty
# first_name (string), last_name (string), phone (string)
# email (email), created_date (date), description (text)
# category (foreing key), show (boolean), owner (foreing key)
# picture (image)

class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return f'{self.name}'

class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50)
    email = models.EmailField(max_length=254, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m/')
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        blank=True, null=True
        )
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True, null=True
    )

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

djangoapp/contact/forms.py
from contact.models import Contact
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import password_validation

class ContactForm(forms.ModelForm):
    picture = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                'accept': 'image/*',
            }
        )
    )

    class Meta:
        model = Contact
        fields = 'first_name', 'last_name', 'phone', 'email', 'description', 'category', 'picture',
        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'Ensira o texto aqui.'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Ensira o texto aqui.'}),
            'phone': forms.TextInput(attrs={'placeholder': 'Ensira o número aqui.'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Ensira o email aqui.'}),
            'description': forms.Textarea(attrs={'placeholder': 'Ensira a descrição aqui.'}),
        }
        help_texts  = {
            'first_name': ('Ajuda'),
        }

    def clean(self):
        cleaned_data = self.cleaned_data
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        if first_name == last_name:
            msg = ValidationError(
                'Primeiro nome não pode ser igual ao segundo',
                code='invalid'
            )

            self.add_error('first_name', msg)
            self.add_error('last_name', msg)

        return super().clean()
    
    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')

        if first_name == 'ABC':
            self.add_error(
                'first_name',
                ValidationError(
                    'veio do error',
                    code='invalid'
                ),   
            )

        return first_name

class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(
        required=True,
        error_messages={
            'required': 'Campo obrigatório'
        }
    )
    last_name = forms.CharField(required=True)

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username', 'password1', 'password2',
        )

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            self.add_error(
                'email',
                ValidationError('Já existe este e-mail', code='invalid')
            )
        return email

class RegisterUpdateForm(forms.ModelForm):
    first_name = forms.CharField(
        label="Primeiro nome",
        min_length=2,
        max_length=30,
        required=True,
        error_messages={
            'min_length': 'O nome precisa conter mais de duas letrar'
        }
    )
    last_name = forms.CharField(
        label="Segundo nome",
        min_length=2,
        max_length=30,
        required=True,
        error_messages={
            'min_length': 'O nome precisa conter mais de duas letrar'
        }
    )
    email = forms.EmailField(required=True)

    password1 = forms.CharField(
        label="Senha",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-passaword"}),
        help_text=password_validation.password_validators_help_text_html(),
        required=False,
    )

    password2 = forms.CharField(
        label="Confirmar senha",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-passaword"}),
        help_text=password_validation.password_validators_help_text_html(),
        required=False,
    )

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username', 
        )
    
    def save(self, commit=True):
        password = self.cleaned_data.get('password1')
        user = super().save(commit=False)

        if password:
            user.set_password(password)
        if commit:
            user.save()
        
        return user

    def clean(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 or password2:
            if password1 != password2:
                self.add_error(
                    'password2',
                    ValidationError('Senhas não batem')
                )

        return super().clean()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        current_email = self.instance.email

        if current_email != email:
            if User.objects.filter(email=email).exists():
                self.add_error(
                    'email',
                    ValidationError('Já existe este e-mail', code='invalid')
                )
        return email
    
    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        if password1:
            try: 
                password_validation.validate_password(password1)
            except ValidationError as errors:
                self.add_error(
                    'password1',
                    ValidationError(errors)
                    )

        return password1

djangoapp/contact/views/contact_forms.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from contact.forms import ContactForm
from contact.models import Contact
from django.urls import reverse

@login_required(login_url='contact:login')
def create(request):
    form_action = reverse('contact:create')

    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.first_name = contact.first_name.strip()
            contact.last_name = contact.last_name.strip()
            contact.phone = contact.phone.strip()
            contact.email = contact.email.strip()
            contact.description = contact.description.strip()
            contact.owner = request.user
            contact.save()
            
            return redirect('contact:update', contact_id=contact.pk)
        
        return render(request, 'pages/contact/create.html', {'form': form, 'form_action': form_action})

    return render(
        request,
        'contact/pages/create.html',
        {
            'form': ContactForm(),
            'form_action': form_action,
        }
    )

@login_required(login_url='contact:login')
def update(request, contact_id):
    contact = get_object_or_404(
        Contact, pk=contact_id, show=True, owner=request.user
    )
    form_action = reverse('contact:update', args=(contact_id,))

    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES, instance=contact)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.first_name = contact.first_name.strip()
            contact.last_name = contact.last_name.strip()
            contact.phone = contact.phone.strip()
            contact.email = contact.email.strip()
            contact.description = contact.description.strip()
            contact.save()
            
            return redirect('contact:update', contact_id=contact.pk)
        
        return render(request, 'contact/create.html', {'form': form, 'form_action': form_action})
          
    return render(
        request,
        'contact/pages/create.html',
        {'form': ContactForm(instance=contact), 'form_action': form_action}
    )

@login_required(login_url='contact:login')
def delete(request, contact_id):
    contact = get_object_or_404(
        Contact, pk=contact_id, show=True, owner=request.user
    )
    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        contact.delete()
        return redirect('contact:index')

    return render(
        request,
        'contact/pages/contact.html',
        {
            'contact': contact,
            'confirmation': confirmation,
        }
    )

djangoapp/contact/views/contact_view.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.db.models import Q
from contact.models import Contact


def index(request):
    contacts = Contact.objects\
        .filter(show=True)\
        .order_by('-id')

    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
    }

    return render(
        request,
        'contact/pages/index.html',
        context,
    )

def search(request):
    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        return redirect('contact:index')

    contacts = Contact.objects\
        .filter(show=True)\
        .filter(
            Q(first_name__icontains=search_value) |
            Q(last_name__icontains=search_value) |
            Q(email__icontains=search_value) |
            Q(phone__icontains=search_value)
        ) \
        .order_by('-id')
    
    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)


    context = {
        'page_obj': page_obj,
        'search_value': search_value
    }

    return render(
        request,
        'contact/pages/index.html',
        context,
    )

def contact(request, contact_id):
    consulta = get_object_or_404(
        Contact, pk=contact_id, show=True
    )
    title = f'de {consulta.first_name} {consulta.last_name}'

    context = {
        'title': title,
        'contact': consulta,
    }

    return render(
        request,
        'contact/pages/contact.html',
        context
    )

djangoapp/contact/views/user_forms.py
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from contact.forms import RegisterForm, RegisterUpdateForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required

def register(request):
    form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Usuário registrado')
            return redirect('contact:login')


    return render(
        request,
        'contact/pages/register.html',
        {
            'form': form
        }
    )

def login_view(request):
    form = AuthenticationForm(request)

    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            messages.success(request, 'Logado com sucesso!')
            return redirect('contact:index')

        messages.error(request, 'Login inválido!')


    return render(
        request,
        'contact/pages/login.html',
        {
            'form': form
        }
    )

@login_required(login_url='contact:login')
def logout_view(request):
    auth.logout(request)
    return redirect('contact:login')

@login_required(login_url='contact:login')
def user_update(request):
    form = RegisterUpdateForm(instance=request.user)

    if request.method == 'POST':
        form = RegisterUpdateForm(data=request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('contact:user_update')
        
        return render(
            request,
            'contact/pages/register.html',
            {
                'form':form
            }
        )

    return render(
        request,
        'contact/pages/register.html',
        {
            'form':form
        }
    )

djangoapp/contact/templates/contact/partials/_head.html
{% load static %}
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Agenda {{ title }}</title>
<link rel="stylesheet" href="{% static 'contact/css/style.css' %}">

djangoapp/contact/templates/contact/partials/_header.html
<header class="header">
  <h1 class="header-heading">
    <a href="{% url 'contact:index' %}" class="header-link">
      Agenda
    </a>
  </h1>

  <nav class="menu">
    <ul class="menu-list">
      {% if user.is_authenticated %}
        <li class="menu-item">
          <a href="{% url "contact:create" %}" class="menu-link">Create</a>
        </li>
        <li class="menu-item">
          <a href="{% url "contact:user_update" %}" class="menu-link">Profile</a>
        </li>
        <li class="menu-item">
          <a href="{% url "contact:logout" %}" class="menu-link">Logout</a>
        </li>
      {% else %}
        <li class="menu-item">
          <a href="{% url "contact:login" %}" class="menu-link">Login</a>
        </li>
        <li class="menu-item">
          <a href="{% url "contact:register" %}" class="menu-link">Register</a>
        </li>
      {% endif %}> 
    </ul>
  </nav>

  <div class="search">
    <form 
      action="{% url "contact:search" %}" 
      method="GET"
    >
      <input 
        type="search" 
        class="search-input"
        placeholder="Search"
        id="search"
        name="q"
        value="{{ search_value }}"
      >
    </form>
  </div>
</header>

djangoapp/contact/templates/contact/partials/_messages.html
{% if messages %}
  {% for message in messages %}
    <div class="message {{ message.tags }}">
      {{ message }}
    </div>
  {% endfor %}
{% endif %}

djangoapp/contact/templates/contact/partials/_pagination.html
{% if page_obj %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1&q={{ search_value }}">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endif %}

djangoapp/contact/templates/contact/partials/_user-form.html
<form 
action="{{ form_action }}"
method="POST"
enctype="multipart/form-data"
>
{% csrf_token %}

<div class="form-content">
  {% for field in form %}
    <div class="form-group">
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {{ field }}
      {{ field.errors }}
    </div>

  {% endfor %}
</div>

{% if form.non_field_errors %}
<div class="form-content">
  <div class="form-group">
    <div class="message error">
      {{ form.non_field_errors }}
    </div>
  </div>
</div>
{% endif %}

<div class="form-content">
  <div class="form-group">
    <button class="btn" type="submit">Send</button>
  </div>
</div>

</form>

djangoapp/contact/templates/contact/partials/table.html
<div class="responsive-table">
  <table class="contacts-table">
    <caption class="table-caption ">
      Contact
    </caption>

    <thead>
      <tr class="table-row table-row-header">
        <th class="table-header">ID</th>
        <th class="table-header">First Name</th>
        <th class="table-header">Last Name</th>
        <th class="table-header">Phone</th>
        <th class="table-header">E-mail</th>
      </tr>
    </thead>

    <tbody>
      {% for contact in page_obj %}
        <tr class="table-row">
            <td class="table-cel">
              <a class="table-link" href="{% url "contact:contact" contact.id %}">
                {{ contact.id }}
              </a>
            </td>
            <td class="table-cel">
              {{ contact.first_name }}
            </td>
            <td class="table-cel">
              {{ contact.last_name }}
            </td>
            <td class="table-cel">
              {{ contact.phone }}
            </td>
            <td class="table-cel">
              {{ contact.email }}
            </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>